name: 🌐 Nuova normalizzazione titolo
description: Proponi una coppia MAL → AnimeSaturn da aggiungere alla funzione normalizeTitleForSearch
title: "[NORMALIZZA]: "
labels: ["normalizzazione"]

body:
  - type: markdown
    attributes:
      value: |
        Compila i campi sottostanti seguendo l’esempio:
        | Campo | Esempio |
        |-------|---------|
        | MAL English name | incolla qui quello che trovi sul sito MAL il titolo sotto in grigio scuro |
        | AnimeSaturn name | incolla qui il titolo di AnimeSaturn senza sub ita o ita |

# Adare su https://myanimelist.net/ cercare il titolo e usare il nome in basso al titolo originale (è grigio più scuro) 
#
# Per AnimeSatur andare su https://www.animesaturn.cx/ cercare il titolo, 
# apritelo e copiate il nome del titolo senza info sulla lingua sub ita o (ITA) copiare solamente il nome
# per esempio Dan Da Dan Sub ITA, copiare solamente Dan Da Dan

  - type: markdown
    attributes:
      value: |
        ⚠️ I dati che inserisci nei campi qui sotto saranno riportati come testo semplice nell’issue. Non modificare i titoli (### MAL English name, ### AnimeSaturn name) per permettere l’automazione!
        📝 Istruzioni MAL : Adare su https://myanimelist.net/ cercare il titolo e usare il nome in basso al titolo originale (è grigio più scuro) 
        📝 Istruzioni AnimeSaturn : Per AnimeSatur andare su https://www.animesaturn.cx/ cercare il titolo, 
            apritelo e copiate il nome del titolo senza info sulla lingua sub ita o (ITA) copiare solamente il nome
            per esempio Dan Da Dan Sub ITA, copiare solamente Dan Da Dan
       
  - type: input
    id: mal_name
    attributes:
      label: MAL English name
      placeholder: Slam Dunk National Domination! Sakuragi Hanamichi
    validations:
      required: true

  - type: input
    id: as_name
    attributes:
      label: AnimeSaturn name
      placeholder: Slam Dunk Zenkoku Seiha Da! Sakuragi Hanamichi
    validations:
      required: true

  - type: checkboxes
    id: conferme
    attributes:
      label: Conferme
      options:
        - label: Ho controllato che la coppia non sia già presente nel file
          required: true
